### ISSUE TITLE
`concat` should return most specific type possible

### ISSUE THREAD

**Issue by rsetaluri** [phanrahan/magma#1006]
Right now `concat` seems to return `Array[N, T]` for all invocations, e.g. `concat(SInt(), UInt()) : Array[N, Bit]`. We should instead maintain the most specific type as possible:

* If any argument to concat is `Array[Bit]` then the output should be `Array[Bit]`
* Otherwise, if any argument to concat is `Bits` then the output should be `Bits`
* If all arguments are `SInt` or all arguments are `UInt`, then return `SInt` and `UInt`, respectively
* In all other cases (e.g. mixed `SInt` and `UInt`) return `Bits`

**Comment by leonardt** [comment]
the mux type inference logic implements this by traversing the class hierarchy (e.g. if one type is the subclass of the other, upcast it to the ancestor class).  It would be good to make sure both functions are using the same logic so we avoid code duplication.  I think the `mux` logic is a bit more general since it handles all values, not just arrays, so we may not want/need to drop it in for concat but maybe it could just work.

**Comment by leonardt** [comment]
Relevant code: https://github.com/phanrahan/magma/blob/master/magma/primitives/mux.py#L72

**Comment by ghhuang** [comment]
Just want to make sure if we concat(Bit, Bit) or concat(Bit, Bits), it will return Bits in both cases.

**Comment by rsetaluri** [comment]
@leonardt good point. I think there's a general principle here. If we view the inheritance pattern as a tree, then we want the "youngest" node that is an ancestor (or self) to all other nodes. Let me try to implement that next.

**Comment by rsetaluri** [comment]
https://stackoverflow.com/questions/58290137/how-to-find-most-recent-common-ancestor-base-type-of-several-types-in-python

**Comment by rsetaluri** [comment]
ok, check out the LCA pattern
