### ISSUE TITLE
Recent changes broke garnet/mantle

### ISSUE THREAD

**Issue by Kuree** [phanrahan/magma#1020]
https://github.com/phanrahan/magma/commit/cb076eb5d4de94072d506d993b8ee6c288a6756f is causing errors in https://github.com/StanfordAHA/garnet/runs/5417103429?check_suite_focus=true#step:6:227

EDIT:
After reading the error message carefully, it seems like mantle is out of sync.

**Comment by leonardt** [comment]
@rsetaluri can you take a look at this? I hotfixed this on master by just moving the old bitutils file to mantle and patching the functions in since they're used in a lot of places.  Not sure if we want to update all that old code since we removed a bunch of the functions being used, or just keep the old bitutils around there for backwards compat.

**Comment by rsetaluri** [comment]
@leonardt thanks for patching. IMO we can keep this hack (I'll clean it up and actually move the functions into mantle). When we update to mantle2 I imagine these generators will go away anyway.

**Comment by leonardt** [comment]
Closing this then.
